### ISSUE TITLE
[bug] not working with ReactMarkdown

### ISSUE THREAD

**Issue by xaota** [remcohaszing/rehype-mermaid#22]
```tsx
import rehypeMermaid from 'rehype-mermaid';
import ReactMarkdown from 'react-markdown';

const markdown = `
### Test mermaid plot

\`\`\`mermaid
graph TD;
  A-->B;
  A-->C;
  B-->D;
  C-->D;
\`\`\`
`
...

return (
  <ReactMarkdown
    rehypePlugins={[ rehypeMermaid ]}
  >
    {markdown}
  </ReactMarkdown>
);
```

throws error to console
```
react-dom-client.development.js:7445 Error: `runSync` finished async. Use `run` instead
    at assertDone (index.js:1273:1)
    at Function.runSync (index.js:952:1)
    at Markdown (index.js:208:1)
    at react-stack-bottom-frame (react-dom-client.development.js:22428:1)
    at renderWithHooks (react-dom-client.development.js:5757:1)
    at updateFunctionComponent (react-dom-client.development.js:8018:1)
    at beginWork (react-dom-client.development.js:9683:1)
    at runWithFiberInDEV (react-dom-client.development.js:543:1)
    at performUnitOfWork (react-dom-client.development.js:15044:1)
    at workLoopSync (react-dom-client.development.js:14870:39)

The above error occurred in the <Markdown> component.

React will try to recreate this component tree from scratch using the error boundary you provided, RenderErrorBoundary.
```

stack - react-19

**Comment by remcohaszing** [comment]
Duplicate of #1
